apiVersion: v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-app
spec:
  replicas: 3                              # Number of Pod replicas
  selector:  
    matchLabels:
      app: nginx-app                       # Must match Pod template labels
  template:
    metadata:
      labels: nginx-app
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            containerPort: 80  